config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/index', to: 'static_pages#home'
  get '/newsletter', to: 'static_pages#newsletter'
  get '/support', to: 'static_pages#support'
  get '/about', to: 'static_pages#about'
  get '/tos', to: 'static_pages#tos'

  # Defines the root path route ("/")
  root "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  validate :acceptable_image
  validates :image, presence: :true
  validates :title, presence: :true
  validates :description, presence: :true
  validates :embedcode, presence: :true

  has_one_attached :image

  default_scope { order(id: :desc) }

  def acceptable_image
    acceptable_types = ["image/jpeg", "image/png"]
    errors.add(:image, "must be JPEG or PNG") unless acceptable_types.include?(image.content_type)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :admin_email

  def admin_email
    allowed_emails = ["caleb@calebstein.net", "jameslyonsweiler@gmail.com"]
    errors.add(:email, "not authorized") unless allowed_emails.include?(email)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]

  # GET /courses or /courses.json
  def index
    @title = 'Self-Paced Courses'
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
    @title = @course.title
  end

  # GET /courses/new
  def new
    @title = 'New Course'
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @title = 'Edit course'
  end

  # POST /courses or /courses.json
  def create
    @title = 'New Course'
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    @title = 'Edit course'
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:image, :description, :title, :subtitle, :embedcode, :released)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @title = 'IPAK EDU Self-Paced Streaming'
  end

  def newsletter
    @title = 'Newsletter'
  end

  def support
    @title = 'Support'
  end

  def about
    @title = 'About'
  end

  def tos
    @title = 'Terms of Use'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @title = "Sign In"
    super
  end

  # POST /resource/sign_in
  def create
    @title = "Sign In"
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/_course.html.erb
<h5 class="pt-2"><em><%= @course.subtitle %></em></h5>
<%== @course.embedcode %>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <p><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</p>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :embedcode, style: "display: block" %>
    <%= form.text_field :embedcode %>
  </div>

  <div>
    <%= form.label :released, style: "display: block" %>
    <%= form.check_box :released %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="text-container">
  <p>Editing course</p>
  <%= render "form", course: @course %>
  <%= button_to "Destroy this course", @course, method: :delete, data: { turbo_confirm: "Confirm delete?" } %>
</div>

app/views/courses/index.html.erb
<div class="course-cards" id="artlist">
  <% @courses.each do |course| %>
    <% if user_signed_in? %>
      <% unless course.released %>
        <div>
          <%= link_to course, style: "background-color: var(--nord3)" do %>
            <%= tag.div class: "image-container" do %>
              <%= image_tag course.image, class: "course-image" %>
            <% end %>
            <%= tag.span course.description, class: "course-desc" %>
            <%= tag.p course.title %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <% if course.released %>
      <div>
        <%= link_to course do %>
          <%= tag.div class: "image-container" do %>
            <%= image_tag course.image, class: "course-image" %>
          <% end %>
          <%= tag.span course.description, class: "course-desc" %>
          <%= tag.p course.title %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="text-container">
  <p>New Course</p>
  <%= render "form", course: @course %>
</div>

app/views/courses/show.html.erb
<div class="video-container">
  <%= render 'course' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag "favicon.png" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script type="text/javascript" src="https://play.webvideocore.net/js/vapp.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>
  </head>

  <body class="d-flex flex-column bg-light" style="padding-top:72px;min-height:100svh">
    <div class="container text-center">
      <%= render 'public/navbar' %>
      <h1 data-turn-enter data-turn-exit><%= @title %></h1>
    </div>
    <div class="container border text-center shadow flex-grow-1">
      <div class="row justify-content-center p-4" data-turn-enter data-turn-exit>
        <%= yield %>
      </div>
    </div>
    <div class="container">
      <%= render 'public/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= image_tag "logo.png", style: "width:256px;height:auto;" %>
<p>Learn for yourself. Learn for your family. Learn for your society.</p>
<p>Our collective future depends on educated, informed, and active citizens.</p>
<p>You are here because you want to be better informed with firm foundations for your perspectives and views. We teach, not indoctrinate. </p>

app/views/static_pages/home.html.erb
<%= image_tag "logo.png", style: "width:256px;height:auto;" %>
<p>Welcome to the IPAK EDU Self-Paced Courses Streaming platform!</p>
<p>Here you will find courses previously offered live on <a target="_blank" href="https://ipak-edu.org/">ipak-edu.org</a> available in a self-paced streaming format.</p>

app/views/static_pages/newsletter.html.erb
<p>Subscribe to the newsletter using the form below:</p>
<iframe src="https://popularrationalism.substack.com/embed" width="480" height="170" frameborder="0" scrolling="no"></iframe>

app/views/static_pages/support.html.erb
    <script type="text/javascript">
        (function() {
            emailjs.init('V4JqfTzqfz6-Dlc_U');
        })();
    </script>
    <script type="text/javascript">
        window.addEventListener("turbo:load", () => {
            document.getElementById('contact-form').addEventListener('submit', function(event) {
                event.preventDefault();
                document.getElementById("sending-text").innerHTML = '<div class="loader"></div>Sending...';
                // generate a five digit number for the contact_number variable
                this.contact_number.value = Math.random() * 100000 | 0;
                // these IDs from the previous steps
                emailjs.sendForm('service_fdws8as', 'template_3utipak_support', this)
                    .then(function() {
                        console.log('SUCCESS!');
                        document.getElementById("contact-form").reset();
                    }, function(error) {
                        console.log('FAILED...', error);
                    });
            });
        } );
    </script>
<p>If you need assistance with any part of this site or the streaming service, please use the form below and we'll get back to you as soon as possible.</p>
<form id="contact-form">
  <input type="hidden" name="contact_number">
  <div class="form-floating mb-3">
    <input class="form-control" type="text" name="user_name" placeholder="Name" required>
    <label for="user_name">Name</label>
  </div>
  <div class="form-floating mb-3">
    <input class="form-control" type="email" name="user_email" placeholder="Email" required>
    <label for="user_email">Email</label>
  </div>
  <div class="form-floating mb-3">
    <textarea style="height:128px" class="w-100 form-control" name="message" placeholder="Message" required></textarea>
    <label for="message">Message</label>
  </div>
  <input class="w-100" type="submit" value="Send">
</form>
<p><br>The source code for this site is hosted on <a target="_blank" href="https://github.com/calebstein1/ipak-ppv-2">GitHub</a>, and you're more than welcome to open an issue or feature request there as well.</p>

app/views/static_pages/tos.html.erb
<div class="text-container">
  <p>Each purchase of a full course or single lecture grants you a non-exclusive license to view the purchased course or lecture for your own personal, non-commercial use using the player software embedded on this site.</p>
  <p>You may use each purchased license to view the content on up to four unique devices at a time.</p>
  <p>No purchase of any license on this site grants you any rights to the trademarks used on this site or any content hosted on this site. All trademark rights are held by IPAK EDU or the instructors/lecturers who have created the content displayed or hosted on this site.</p>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>